"""
AVAXTASwapMA Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import AVAXTASwapMAStrategy
except ImportError:
    from strategy import AVAXTASwapMAStrategy

__all__ = [
    "AVAXTASwapMAStrategy",
]
